### PR TITLE
Seven minute workout

### PR DESCRIPTION
**Pull request by misterhay**
A notebook that generates 7-minute workouts

### CODE REVIEW

**Comment by misterhay** [comment]
Looks like CI is failing because gtts is not working on the Callysto Hub. It works locally however, so some troubleshooting is required.

**Comment by ianabc** [comment]
It seems to work with gtts 2.2.2 on a development hub. This should come along in the next image rebuild in a couple of days.

**Comment by misterhay** [comment]
> It seems to work with gtts 2.2.2 on a development hub. This should come along in the next image rebuild in a couple of days.
> 
> EDIT: The new image is available on hub.callysto.ca now if you want to try triggering travis avain.

It worked, thank you for taking care of that.

**Comment by byrcyb** [comment]
Tried the workouts, they are tough but fun! It would be good to have instructions on how to stop the seven minute workout if folks want to stop it early as it's not obvious how you would stop it. Also with the random workout, we got the same exercise back-to-back a couple of times during the 7 minutes so it might be nice to be able to avoid that (but it's not critical as it's still a good workout).

**Comment by misterhay** [comment]
> Tried the workouts, they are tough but fun! It would be good to have instructions on how to stop the seven minute workout if folks want to stop it early as it's not obvious how you would stop it. Also with the random workout, we got the same exercise back-to-back a couple of times during the 7 minutes so it might be nice to be able to avoid that (but it's not critical as it's still a good workout).

Great points. I've updated the instructions and the random activity picker.

**Review by byrcyb — APPROVED** [review]
Looks good.

**Pull request merged**
