### PR TITLE
Cc 74 order of operations

### PR DESCRIPTION
**Pull request by n-vachon**
Content review has been completed. Two small changes have been made since the content review, one being technical.

### CODE REVIEW

**Comment by inygy** [comment]
You need to do input validation on the first practice question, for example if I input -1 I get a Type Error.

**Comment by inygy** [comment]
I am still getting the type error with input of -1

**Comment by nickurak** [comment]
I'm *sometimes* seeing a type error, even with the correct answer added. Specifically, if I:
- Select Kernel:Restart and Clear output
- Select Cell:Run All
- Type 20.5 into that text field and hit 'enter'

I get this error:
`TypeError: display() missing 1 required positional argument: 'b'`

Full traceback here: https://gist.github.com/nickurak/b3131c37dbd8d7ac66520ab58fc581c6

**Comment by nickurak** [comment]
The issue I was hitting appears to be that the display() function is redefined later on. If you do a "Run All" of the cells, that display function ends up being a totally different function, that needs a 'b' parameter passed to it.

The way I discovered this was to us the `inspect` module to print out the code of the `display` function just before executing it, like this:

```
def check(a):
    op1.value = ''
    op2.value = ''
    op3.value = ''
    IPython.display.clear_output(wait=False)
    import inspect
    print(inspect.getsource(display))
    display()
    if answer.value == 20.5:
        print("You are correct!")
    else:
        print("Sorry, that's not the right answer. Which operation did you do first?")
        IPython.display.display(op1)
```

That showed me this output, just before the error and traceback:

```
def display(b):
    IPython.display.clear_output(wait=False)
    IPython.display.display(choice, Start)
    create(choice.value)
    IPython.display.display(ans)
    ans.on_click(on_button)
```

**Comment by sean-fitzpatrick** [comment]
@snimpids Does the last commit from Nicole address the type error? If so, can we move this to staging?

**Pull request merged**
