### PR TITLE
Cc 55 solving problems with permutations: fixed issues

### PR DESCRIPTION
**Pull request by NathanTipper**

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
I've sent a message to Richelle Marynowski about the nPr notation. I think it's probably what students will see in their classroom, in which case alternative notation might cause confusion, even if we don't like the existing notation. (Also, I'm not sure about an alternative for permutations. For combinations, the nCr notation can be replaced with the standard binomial coefficient notation.)

Now is where I throw Nathan under the bus: did you test the code on Firefox, or only on Chrome? There was an issue with some of the sliders in d3 not working on Firefox because they depended on a Chrome-specific library.

+1 on the fruit salad link. (I snuck that in when Nathan wasn't looking)

**Comment by NathanTipper** [comment]
I have fixed many of the problems suggested by Eric. However, I was not able to implement d3 version 4 into the notebook as it breaks. I didn't think this was too big of a deal, but let me know otherwise. In order to get d3 to load on a run all the cells I added a script tag inside each cell referring to d3. It seems to be working so I will just keep like that. I tried the requirejs way and it didn't work. 

As for the problems with the sliders and d3 inside firefox, I can look into it, but everything seems to be working differently firefox. d3 doesn't even seem to be working in my notebook on firefox, so for now I can write a disclaimer saying that it only works on Chrome and try and make a separate firefox notebook. Again, I am still looking into this problem.

**Comment by nickurak** [comment]
While this repository is based on master, it's targeting staging. Master is currently ahead of staging, so this PR (in addition to the CC-55 work) is effectively backporting PRs #83 and #85 into staging (which those two PRs bypassed.

**Comment by NathanTipper** [comment]
Oh, sorry about that. Should I just save my work, delete the branch and then recreate the branch and resubmit the pull request?

**Comment by nickurak** [comment]
@NathanTipper You can. If you don't mind, I could also just fix it in this PR before its merged.

**Comment by sean-fitzpatrick** [comment]
@nickurak if you can fix the PR, please feel free to do so. Let us know if you need Nathan to start over with a clean branch.

**Comment by nickurak** [comment]
Okay, I've pushed in an updated (rebased) version of these changes on top of origin/staging. The content for Mathematics/SolvingProblemsWithPermutations is exactly as it was before.

(For reference, the original git branch is also available at CC-55-SolvingProblemsWithPermutations-unrebased )

That said -- this notebook does still seem to have issues. I haven't been able to run the interactive circles example before or after my changes, and the `Computing $_nP_r$` table isn't showing up to be filled in. I'm considering those fixes out of scope for my current work -- so someone else may want to work on it.

Additional changes to this branch should be done by re-checking-out this branch from github and pushing additional commits back. I'm happy to monitor this PR to watch in case anything does go awry.

**Comment by sean-fitzpatrick** [comment]
@nickurak what browser were you using for testing? One of the reasons this PR went stale is that @NathanTipper had everything running nicely on Chrome, and then we discovered that the way Firefox handled the Javascript for the d3 elements was completely different, and it rendered those elements useless.
I believe we asked around on Slack at the time to see if anyone could come up with a fix, with no success. I haven't heard of problems with d3 and firefox in other notebooks though, so I'm not sure what caused the problems here. Nathan might have more insight than me on this.

**Comment by nickurak** [comment]
I was using Chrome.

**Comment by sean-fitzpatrick** [comment]
OK. I'm checking with Nathan to see if he has time to debug.

**Comment by AlexIsBadWithComputers** [comment]
After taking a quick peek at the notebook and javascript code, I think the fix mentioned at the bottom of this page should fix your `d3` loading issues:

https://training.callysto.ca/coding/troubleshooting

**Pull request closed without merging**
