### PR TITLE
CC-63-Oral-and-Written-Patterns

### PR DESCRIPTION
**Pull request by FordMcLeod**

### CODE REVIEW

**Comment by FordMcLeod** [comment]
Made changes on CC-63 and updated branch. Resolved all the issues stated.

**Comment by AlexIsBadWithComputers** [comment]
@inygy 

I _think_ I managed to find the right way to load `d3` to get the animations working in order with a cell -> run all. I was able to get this working on a fresh checkout on the dev environment which should be identical to hub.callysto.ca. However, I don't want to merge this until someone else can confirm that cell -> run all is working for them as well.

**Comment by AlexIsBadWithComputers** [comment]
As an aside, a lot of the problems in this notebook were caused by two very simple mistakes 
1. Javascript loading was not protected by a function, meaning that consistent name spacing between the files was being over written and causing only one of the widgets to work as both were trying to push data to the same `svg` object. If developers aren't going to wrap animations like this in functions, they need to be aware that variable declarations _are not safe_ between files once its loaded into Jupyter.
2. Loading d3 inside the notebook with `<script>` tags require the cells to be run twice in order for any javascript modules to be loaded in time - unless all your javascript is in the same cell (un imported). Packages like `d3` need to be included with something like 
```javascript
requirejs.config({
    paths: { 
        'd3': ['//cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3'], 
    },                                         // strip .js ^, require adds it back
});

require(['d3'], function(d3) { what you want your script to do} )
```
inside the actual `.js` file _not_ inside the notebook.

**Comment by inygy** [comment]
Thanks for the aside, I’ll add it to the troubleshooting section of the training manual.

**Pull request merged**
