### PR TITLE
Reference remote data files

### PR DESCRIPTION
**Pull request by misterhay**
Updated health, languages, and social studies notebooks to reference data files from https://github.com/callysto/data-files rather than from the current repository.

### CODE REVIEW

**Comment by mlamoureux** [comment]
Today I tested all the changed Jupyter notebooks. All the notebooks in folder "Health" and "SocialStudies" are correct. However, the notebooks in "Science" and in "Mathematics" are incorrect. The URLs in the code still reference the local .csv files, not the files on raw.githubusercontent.com address. This needs to be corrected before the PR is approved. 

There are the files that need correction:
canadian-electricity-generation.ipynb
body-electricity.ipynb
olympics.ipynb
budget-and-banking-assignment.ipynb
outliers-and-central-tendency.ipynb
central-tendency.ipynb
statistical-reasoning.ipynb

**Comment by misterhay** [comment]
Thank you for listing the ones that still needed to be adjusted. Hopefully they've all be updated to reference the remote data files.

**Comment by mlamoureux** [comment]
David has made all the changes I requested, I am ready to approved. 
I just need to remember how one approves a PR!

**Review by mlamoureux — APPROVED** [review]
David has made all the changes and Michael has verified that the remote access of data files works on all the changed notebooks. There is still an issue with "geogebra" installs failing in the notebook (Mathematics) central-tendency.ipynb but I will leave that for another PR>

**Pull request merged**
