### PR TITLE
Restructure directories

### PR DESCRIPTION
**Pull request by lgfunderburk**
Re-categorized notebooks according to https://docs.google.com/spreadsheets/d/1pw-p7uluSa7xWwHYn7ZgQ8jxkHwXnkDJa_NLR44TbS8/edit#gid=0 

Need to confirm these changes are appropriate before adding new URL's to website.

### CODE REVIEW

**Comment by misterhay** [comment]
Looks like the continuous integration failures are in French-Verb-Coding.ipynb, French-Verb-Conjugation.ipynb, and ASL-Leap-Motion.ipynb

I don't think they are big issues, but perhaps something we should look at refactoring after merging this pull request.

**Comment by lgfunderburk** [comment]
Added Line graph notebook @misterhay

**Comment by lgfunderburk** [comment]
@byrcyb  made changes as requested - it seems that it passed the tests after adding #NBVAL_SKIP in the French verb conjugation notebooks. 

Please review and approve once you are ready. 

I will create links for the Callysto website on the spreadsheet.

**Comment by nickurak** [comment]
@byrcyb  To be clear -- ignore there doesn't mean "Merge this without addressing that error" right? It means "Make that test not run, or make the failure ignored automatically", right?

**Comment by byrcyb** [comment]
@nickurak how do you either make the test not run or make the failure be ignored automatically? We could use your help if you know how.

**Comment by nickurak** [comment]
> @nickurak how do you either make the test not run or make the failure be ignored automatically? We could use your help if you know how.

This is documented in the "Skipping Tests" section of the CONTRIBUTING guide

**Comment by lgfunderburk** [comment]
@nickurak  we tried - I used the #NBVAL_SKIP flag, but the errors in the line graph notebook would not be caught as it is not an error due no user input, but rather a Python syntax error. 
The students are asked to complete code within the cells - which will create a bunch of syntax errors we cannot bypass. 
I did not see a command for that kind of error.

**Comment by nickurak** [comment]
I also see the NBVAL skip was removed from the doc by @misterhay recently, so I might be a little out of tune here.

@cmann Was also involved in building the automated testing here, so may have some info.

**Comment by lgfunderburk** [comment]
@misterhay  added latest modifications to Mathematics/CreateInterpretLineGraphs/create-label-and-interpret-line-graphs.ipynb - I notice changes were made on the syntax level. Passing to you for review.

**Comment by lgfunderburk** [comment]
@misterhay  added one extra exercise that was introducing a plotting error
#✏️ Uncomment the line below
#plt.plot(dates, daylight_hours)
This allows the entire notebook to run without syntax errors (before students enter their answers) while also respecting the need not to introduce user inputs - extra code could confuse students.

**Comment by lgfunderburk** [comment]
Leap motion is failing

=================================== FAILURES ===================================
________________________ ASL-Leap-Motion.ipynb::Cell 2 _________________________
Notebook cell execution failed
Cell 2: Cell execution caused an exception
Input:
def maker():
    #a function that lets you look up values in a dictionary
    letters = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    dct = dict()
    for i in range(len(letters)):
        dct[letters[i]] = 'Orientation for ' + '\'' + letters[i] + '\''
    return dct
def finder(key):
    y = maker()
    x = y[str(key)]
    print(x)
try:
    interact(finder, key = widgets.Text(placeholder =' ' , description = 'String',disabled = True));
except:
    pass
    
Traceback:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/ipywidgets/widgets/interaction.py in update(self, *args)
    249                     value = widget.get_interact_value()
    250                     self.kwargs[widget._kwarg] = value
--> 251                 self.result = self.f(**self.kwargs)
    252                 show_inline_matplotlib_plots()
    253                 if self.auto_display and self.result is not None:
<ipython-input-3-9274c9421682> in finder(key)
     10 def finder(key):
     11     y = maker()
---> 12     x = y[str(key)]
     13     print(x)
     14 
KeyError: ''

**Comment by misterhay** [comment]
Added back in the banner files and the changed CONTRIBUTING file

**Pull request merged**
