### PR TITLE
Remove cufflinks in favor of Plotly Express

### PR DESCRIPTION
**Pull request by misterhay**
Switching from cufflinks to Plotly Express

### CODE REVIEW

**Review by BryceHaley — COMMENTED** [review]
- shakespeare and stats looks good;
- mars mission looks good;
- American revolution works fine, if a bit slow;
- electrical conductivity looks fine;
- Concentration and PH has a bug:

nothing renders below: "Now that we have the averages, here is the collected water treatment plant data from the past week. Notice that column 2 is labelled pH. That is what we will be comparing to our averages. Click on the button below to compare the data in a graph."
and if you select a radio option such as "An acid" you get an error on the hub or local:

```---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/opt/conda/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

/opt/conda/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

/opt/conda/lib/python3.8/contextlib.py in __exit__(self, type, value, traceback)
    118         if type is None:
    119             try:
--> 120                 next(self.gen)
    121             except StopIteration:
    122                 return False

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in hold_trait_notifications(self)
   1212                 for changes in cache.values():
   1213                     for change in changes:
-> 1214                         self.notify_change(change)
   1215 
   1216     def _notify_trait(self, name, old_value, new_value):

/opt/conda/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
    604                 # Send new state to front-end
    605                 self.send_state(key=name)
--> 606         super(Widget, self).notify_change(change)
    607 
    608     def __repr__(self):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1225     def notify_change(self, change):
   1226         """Notify observers of a change event"""
-> 1227         return self._notify_observers(change)
   1228 
   1229     def _notify_observers(self, event):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in _notify_observers(self, event)
   1262                 c = getattr(self, c.name)
   1263 
-> 1264             c(event)
   1265 
   1266     def _add_notifiers(self, handler, name, type):

/opt/conda/lib/python3.8/site-packages/ipywidgets/widgets/widget_selection.py in _propagate_index(self, change)
    233             self.label = label
    234         if self.value is not value:
--> 235             self.value = value
    236 
    237     @validate('value')

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
    602             raise TraitError('The "%s" trait is read-only.' % self.name)
    603         else:
--> 604             self.set(obj, value)
    605 
    606     def _validate(self, obj, value):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in set(self, obj, value)
    591             # we explicitly compare silent to True just in case the equality
    592             # comparison above returns something other than True/False
--> 593             obj._notify_trait(self.name, old_value, new_value)
    594 
    595     def __set__(self, obj, value):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in _notify_trait(self, name, old_value, new_value)
   1215 
   1216     def _notify_trait(self, name, old_value, new_value):
-> 1217         self.notify_change(Bunch(
   1218             name=name,
   1219             old=old_value,

/opt/conda/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
    604                 # Send new state to front-end
    605                 self.send_state(key=name)
--> 606         super(Widget, self).notify_change(change)
    607 
    608     def __repr__(self):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1225     def notify_change(self, change):
   1226         """Notify observers of a change event"""
-> 1227         return self._notify_observers(change)
   1228 
   1229     def _notify_observers(self, event):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in _notify_observers(self, event)
   1262                 c = getattr(self, c.name)
   1263 
-> 1264             c(event)
   1265 
   1266     def _add_notifiers(self, handler, name, type):

<ipython-input-19-c24195159375> in check8(a)
      9     IPython.display.clear_output()
     10     display8()
---> 11     if table_RD[0].iloc[2, 7] >= 7.5 and answers8.value == 'An acid':
     12         print("That's right! Adding an acid to Rossdale's water will make it more like tap water because it's too alkaline.")
     13     else:

NameError: name 'table_RD' is not defined```

**Comment by BryceHaley** [comment]
mars mission looks good.

**Comment by BryceHaley** [comment]
Concentration and PH has a bug:

nothing renders below: "Now that we have the averages, here is the collected water treatment plant data from the past week. Notice that column 2 is labelled pH. That is what we will be comparing to our averages. Click on the button below to compare the data in a graph."
and if you select a radio option such as "An acid" you get an error:

```---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/opt/conda/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

/opt/conda/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

/opt/conda/lib/python3.8/contextlib.py in __exit__(self, type, value, traceback)
    118         if type is None:
    119             try:
--> 120                 next(self.gen)
    121             except StopIteration:
    122                 return False

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in hold_trait_notifications(self)
   1212                 for changes in cache.values():
   1213                     for change in changes:
-> 1214                         self.notify_change(change)
   1215 
   1216     def _notify_trait(self, name, old_value, new_value):

/opt/conda/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
    604                 # Send new state to front-end
    605                 self.send_state(key=name)
--> 606         super(Widget, self).notify_change(change)
    607 
    608     def __repr__(self):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1225     def notify_change(self, change):
   1226         """Notify observers of a change event"""
-> 1227         return self._notify_observers(change)
   1228 
   1229     def _notify_observers(self, event):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in _notify_observers(self, event)
   1262                 c = getattr(self, c.name)
   1263 
-> 1264             c(event)
   1265 
   1266     def _add_notifiers(self, handler, name, type):

/opt/conda/lib/python3.8/site-packages/ipywidgets/widgets/widget_selection.py in _propagate_index(self, change)
    233             self.label = label
    234         if self.value is not value:
--> 235             self.value = value
    236 
    237     @validate('value')

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
    602             raise TraitError('The "%s" trait is read-only.' % self.name)
    603         else:
--> 604             self.set(obj, value)
    605 
    606     def _validate(self, obj, value):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in set(self, obj, value)
    591             # we explicitly compare silent to True just in case the equality
    592             # comparison above returns something other than True/False
--> 593             obj._notify_trait(self.name, old_value, new_value)
    594 
    595     def __set__(self, obj, value):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in _notify_trait(self, name, old_value, new_value)
   1215 
   1216     def _notify_trait(self, name, old_value, new_value):
-> 1217         self.notify_change(Bunch(
   1218             name=name,
   1219             old=old_value,

/opt/conda/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
    604                 # Send new state to front-end
    605                 self.send_state(key=name)
--> 606         super(Widget, self).notify_change(change)
    607 
    608     def __repr__(self):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1225     def notify_change(self, change):
   1226         """Notify observers of a change event"""
-> 1227         return self._notify_observers(change)
   1228 
   1229     def _notify_observers(self, event):

/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py in _notify_observers(self, event)
   1262                 c = getattr(self, c.name)
   1263 
-> 1264             c(event)
   1265 
   1266     def _add_notifiers(self, handler, name, type):

<ipython-input-19-c24195159375> in check8(a)
      9     IPython.display.clear_output()
     10     display8()
---> 11     if table_RD[0].iloc[2, 7] >= 7.5 and answers8.value == 'An acid':
     12         print("That's right! Adding an acid to Rossdale's water will make it more like tap water because it's too alkaline.")
     13     else:

NameError: name 'table_RD' is not defined```

This was observed both when running locally and on the hub.

**Comment by BryceHaley** [comment]
electrical conductivity looks fine

**Comment by BryceHaley** [comment]
American revolution works fine, if a bit slow.

**Comment by BryceHaley** [comment]
In concentration-and-ph the plotly plot now loads. However, attempting to select one of the radio buttons below the plot,
"What should be added to Rossdale's water to make it more like tap water?", still errors out with the same error listed in the earlier comment.

```NameError: name 'table_RD' is not defined```

**Comment by misterhay** [comment]
Thanks for catching that, it should be working now.

**Comment by BryceHaley** [comment]
New and exciting bugs.
If I run:
```
import plotly.express as px
rossdale = pd.read_html('http://apps.epcor.ca/DailyWaterQuality/Default.aspx?zone=Rossdale', header=0)[0]
els = pd.read_html('http://apps.epcor.ca/DailyWaterQuality/Default.aspx?zone=ELS', header=0)[0]
combined_data = pd.DataFrame()
combined_data['Rossdale'] = rossdale.iloc[2][1:]
combined_data['ELS'] = els.iloc[2][1:]
for i, row in output_data.iterrows():
    combined_data[row.name] = row['Average pH']
fig = px.line(combined_data.astype(float), x=combined_data.index, y=combined_data.columns)
fig.update_layout(xaxis_title='Date', yaxis_title='pH').show()
```
The following error occurs:
```
ValueError                                Traceback (most recent call last)
<ipython-input-22-23f983b02a49> in <module>
      7 for i, row in output_data.iterrows():
      8     combined_data[row.name] = row['Average pH']
----> 9 fig = px.line(combined_data.astype(float), x=combined_data.index, y=combined_data.columns)
     10 fig.update_layout(xaxis_title='Date', yaxis_title='pH').show()

/opt/anaconda3/envs/pie-politics/lib/python3.8/site-packages/pandas/core/generic.py in astype(self, dtype, copy, errors)
   5544         else:
   5545             # else, only a single dtype is given
-> 5546             new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
   5547             return self._constructor(new_data).__finalize__(self, method="astype")
   5548 

/opt/anaconda3/envs/pie-politics/lib/python3.8/site-packages/pandas/core/internals/managers.py in astype(self, dtype, copy, errors)
    593         self, dtype, copy: bool = False, errors: str = "raise"
    594     ) -> "BlockManager":
--> 595         return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
    596 
    597     def convert(

/opt/anaconda3/envs/pie-politics/lib/python3.8/site-packages/pandas/core/internals/managers.py in apply(self, f, align_keys, **kwargs)
    404                 applied = b.apply(f, **kwargs)
    405             else:
--> 406                 applied = getattr(b, f)(**kwargs)
    407             result_blocks = _extend_blocks(applied, result_blocks)
    408 

/opt/anaconda3/envs/pie-politics/lib/python3.8/site-packages/pandas/core/internals/blocks.py in astype(self, dtype, copy, errors)
    593             vals1d = values.ravel()
    594             try:
--> 595                 values = astype_nansafe(vals1d, dtype, copy=True)
    596             except (ValueError, TypeError):
    597                 # e.g. astype_nansafe can fail on object-dtype of strings

/opt/anaconda3/envs/pie-politics/lib/python3.8/site-packages/pandas/core/dtypes/cast.py in astype_nansafe(arr, dtype, copy, skipna)
    993     if copy or is_object_dtype(arr) or is_object_dtype(dtype):
    994         # Explicit copy, or required since NumPy can't view from / to object.
--> 995         return arr.astype(dtype, copy=True)
    996 
    997     return arr.view(dtype)

ValueError: could not convert string to float: '--'
```

So, the plot does not show and the radio buttons have no functionality.

**Review by BryceHaley — CHANGES_REQUESTED** [review]
see previous comment re: new bug

**Comment by misterhay** [comment]
> see previous comment re: new bug

I can't reproduce that bug on the Hub or locally, but I did notice that the "hide code" means we need those "click to run" buttons back in.

**Review by BryceHaley — APPROVED** [review]
After pulling most recent changes I cannot recreate the last error and the buttons all work.
Approved.

**Pull request merged**
