### PR TITLE
Delete folders and notebooks identified for removal

### PR DESCRIPTION
**Pull request by misterhay**
Files and folders set to be deleted have been copied to [archived-notebooks](https://github.com/callysto/archived-notebooks)

### CODE REVIEW

**Comment by jswan5** [comment]
Notebooks to be deleted line up perfectly with the Google Sheet, looks good to me!

I know there was talk of archiving the notebooks, was that abandoned?

**Comment by byrcyb** [comment]
For your reference @jswan5 here's the archived-notebooks repo https://github.com/callysto/archived-notebooks

**Review by byrcyb — APPROVED** [review]
Changes look good to me too. We'll need to update the curriculum notebooks table on the website so we don't include these anymore. I'll look at updating the website first before merging in these changes.

**Comment by byrcyb** [comment]
Oops, I noticed that we are deleting this notebook and associated files but actually meant to keep it. We deleted the related exercises notebook not that long ago.

`Mathematics/Transformations/transformations.ipynb`

**Comment by misterhay** [comment]
Good catch, thank you. I've re-added that notebook and the associated files.

**Review by byrcyb — APPROVED** [review]
Changes look good now. Thanks for fixing it. Website has been updated too so we are good to merge.

**Pull request merged**
