### PR TITLE
Merge CC-173 branch to staging

### PR DESCRIPTION
**Pull request by byrcyb**
Note, branch is mislabeled as CC-176 whereas it should be CC-173. Merging for UnsaltedCashews who is no longer with the project.

### CODE REVIEW

**Comment by nickurak** [comment]
@cmann Can you tell if the CI failure here is the same class of user-uid/permission issue you've seen elsewhere?

**Comment by inygy** [comment]
If you look at the Travis logs you can see why it failed: `Whitespace is not allowed in notebook paths, these files need to be renamed`

**Comment by nickurak** [comment]
Right, I should have specified the warnings about the pytest cache:  `/opt/conda/lib/python3.6/site-packages/_pytest/cacheprovider.py:126: PytestWarning: could not create cache path /notebooks/Technology/Introduction_To_Python_Classes/.pytest_cache/v/cache/nodeids`

**Comment by inygy** [comment]
We can ignore the cache warning. Pytest attempts to make a cache for performance improvements but cannot since it is running on a read only file system. We could disable the cache creation with `PYTHONDONTWRITEBYTECODE=1 python -m pytest -p no:cacheprovider` however, we may want the cache performance improvement for other tasks. I believe we have it setup so warnings do not fail Travis.

**Comment by cmann** [comment]
Yep the root cause of those warnings is the same UID issue as before where the jupyter user doesn't have permission to write to the bind mount. And also yes, those warnings don't cause pytest to fail so they won't cause the build to fail.

If there's an option to change where the cache dirs get created we could look into that instead of potentially disabling caching entirely. Though we'd also have to attach a volume to the container to store them otherwise they'd disappear between runs.

**Comment by nickurak** [comment]
Closing this in favor of #85, with correct PR metadata.

**Pull request closed without merging**
