### PR TITLE
Deprecated notebooks

### PR DESCRIPTION
**Pull request by lisancao**
Changes mostly include the reformatting salvaged notebooks to meet curriculum standards and moving them into the appropriate directory 

NOTE: DO NOT MERGE AFTER APPROVING REVIEW- in order to properly merge this branch this guide should be followed to ensure that the deprecated_notebooks folder is not automatically merged. http://schacon.github.io/git/git-cherry-pick.html

### CODE REVIEW

**Comment by lisancao** [comment]
**NOTE**: Travis is returning errors for notebooks _that we know are broken from the deprecated_notebooks folder_ along with some other higher level input errors that is probably related. I can try to remove deprecated_notebooks/ and attempt to re-pass Travis

**Comment by lisancao** [comment]
**NOTE:** After removing the folder it seems that the only notebook failing checks is "Introduction to loops and iteration in python", particularly notebook cells 6, 7, and 18. Will take a closer look later on to debug but for now will just remove the notebook and bring it back into deprecated_notebooks/

**Comment by lisancao** [comment]
OK. After reviewing the notebook it is fine to integrate, the errors are either intentional (to demonstrate a particular concept) or because of expected user input that when passed an empty statement to return error messages. 

Issue is, if we keep this notebook in the repo, Travis will consistently mark it as failing checks- to integrate or not to?

**Comment by misterhay** [comment]
It looks like we can safely rewrite the "loops and iterations" notebook to not use `input()`. I'll work on that.

**Comment by misterhay** [comment]
I've rewritten TechnologyStudies/IntroToLoopsAndIteration/intro-to-loops-and-iteration.ipynb, it should be ready to merge into our main branch.

**Pull request merged**
