### PR TITLE
added topics

### PR DESCRIPTION
**Pull request by mrbubbleman**
- Added a section that looks particularly at the **subtopic** column in the Hansard data frame. 
- Added a pie chart that has the _the number of times a topic was spoken_
- Added a section where users can input a particular topic and see which members of Parliament speak regarding the topic
- Added a section which looks at each party's most important topics (top 10 most spoken topics)

### CODE REVIEW

**Review by misterhay — CHANGES_REQUESTED** [review]
Looks good, very good ideas.

A few suggestions:
* The pie chart of topics, perhaps a bar chart (or horizontal bar chart) would communicate better. Alternatively, a pie chart of just the top 10 topics might work.
* We generally try to avoid using `input`, so that the notebook can go all the way through using "Run All". Instead we can have users actually change the value in the code, e.g. `member = 'Garnett Genuis`.
* Underlining text might make it look like a link, try *italics* or **bold**
* For those "Topics" bar charts, the text would be easier to read if they were horizontal bar charts.

Great work, I like how you've given more opportunities for extracting and communicating meaning from the dataset.

**Comment by mrbubbleman** [comment]
Thanks for the potential changes, I'll definitely adjust accordingly.

**Comment by mrbubbleman** [comment]
Changes added
- Changed pie chart into 2 bar graphs which show top 10/bot 10 most spoken topics
- Changed underlining into _italics_
- Removed input and added a comment so users using the notebook can switch between topics
- Changed bar charts to horizontal, also removed the y_axis title as it was too large, and now the graphs are more elegant

**Review by misterhay — APPROVED** [review]
Looks good

**Pull request merged**
