### PR TITLE
Cc 222 sources of energy

### PR DESCRIPTION
**Pull request by jazlynpedersen**
Ready for review

### CODE REVIEW

**Comment by jazlynpedersen** [comment]
Thankyou! I will get on it ASAP!

**Comment by jazlynpedersen** [comment]
@AlexIsBadWithComputers okay I have made all of the changes except I do not what you mean when you say "All your images need to be sourced within the text (unless of course they're licensed for use without credit, which I _think_ the AWS images are)" 

Thanks!!

**Comment by AlexIsBadWithComputers** [comment]
@jazlynpedersen 

Sorry for the confusion! In regards to your last comment, all I mean't by that was if you're using images that aren't yours from the internet, you need to credit the source in something like an image caption.

**Comment by jazlynpedersen** [comment]
I tried to push my changes, let me know if I was successful as I am still not fluent in terminal commands.
Thanks!
Jazlyn

**Comment by sean-fitzpatrick** [comment]
Jazyln made the requested changes, but made some sort of mistake with the git commands when she pushed those changes. (She forgot the message with the git commit. Not really sure why it says the commit came from nbgitpuller...)
We can't figure out why it's failing the Travis CI check though -- no error messages show up in the notebook.

**Comment by sean-fitzpatrick** [comment]
@AlexIsBadWithComputers can you confirm that your changes have been addressed? I think this is otherwise good to go

**Comment by AlexIsBadWithComputers** [comment]
@sean-fitzpatrick @jazlynpedersen 

Sorry for the delay everyone, I was out on vacation far from the world of git. It appears everything is in order and I'll approve the pull request.

**Pull request merged**
