### PR TITLE
CC-161 adding the Ecoglobalization notebook

### PR DESCRIPTION
**Pull request by NathanTipper**

### CODE REVIEW

**Comment by nickurak** [comment]
Apologies, I haven't gotten around to reviewing this one yet. This'll be my next todo item.

**Comment by nickurak** [comment]
@cmann Do you have an approach that's working for these notebooks that write out files that doesn't result in a permission error when run by travis-ci?

**Comment by nickurak** [comment]
That last commit simplified things, but didn't resolve anything.

No real comments beyond that.

**Comment by cmann** [comment]
CI is failing because it's trying to write `data/wiki_data.json`, doesn't matter where it's being done from unfortunately. The real solution is I magically figure out a good fix for the Docker permissions problem. But, if we want this notebook to pass right now there's a few quick fixes:

1. The JSON file is already committed to the repo, so we could just wrap the wrap the code that writes it in a `try: ... except PermissionError: pass` and the later code will just use the existing file.
2. Alternatively we just don't write the file at all and entirely depend on the committed one to keep behaviour consistent between all environments.
3. Write to a path not under the bind mount like `/tmp` instead. The downside is there's nothing there for later code to fallback to if scraping the wiki page fails.

I really don't like modifying legitimate behaviour just to pass tests so I think 1 is the only reasonable solution.

**Pull request closed without merging**
