### PR TITLE
CC 47 root finding algorithms

### PR DESCRIPTION
**Pull request by sltaylor007**
Making a pull request for code review.

### CODE REVIEW

**Comment by AlexIsBadWithComputers** [comment]
## Fixes still required 

1. There is a name error y in one of your plots resulting from this line of code 
screen shot 2019-01-29 at 5 13 30 pm

With the following error 
screen shot 2019-01-29 at 5 13 26 pm

Where your variable `y` is not defined. I'm not clear on where the value for y is coming from, but it will likely need some default values. This error persists in both your "analyze graph" buttons where the student is to enter their own root finding ranges/tolerances. 



## Other Fixes Still Required  

1. Your widgets you need to either warn the user if they haven't hit enter (by checking for a None entry) or to grab it live. Other wise you need to set things up such that hitting enter is not required. Currently it's non-intuitive why a correct answer will be reported as incorrect if the user hasn't hit enter.


But besides that everything looks good. I made a minor change such that your input sanitation propagates.

**Comment by AlexIsBadWithComputers** [comment]
@sltaylor007

Most recent changes fix almost everything! Fantastic work. Unfortunately there's still one quirk that has popped back up in regards to multiple outputs being created by your widgets. For example the screen shot below: 
screen shot 2019-02-14 at 3 48 44 pm

but once that's worked out, I don't see any other fixes that need to be made!

**Comment by AlexIsBadWithComputers** [comment]
Added minor fix on a couple entry widgets, but after this it looks good to go and I have approved the pull request.

**Comment by inygy** [comment]
Make sure the .ipynb_checkpoints are removed before merging.

**Comment by AlexIsBadWithComputers** [comment]
Checkpoints from all places they were hiding have been removed.

**Pull request merged**
