### PR TITLE
A notebook for listening to pronunciation in other languages

### PR DESCRIPTION
**Pull request by misterhay**

### CODE REVIEW

**Comment by misterhay** [comment]
Looks like CI is failing because gtts and googletrans are not working on the Callysto Hub. Both work locally however.

**Comment by ianabc** [comment]
As far as I can tell this is down to google (repeatedly) changing their API. The same issue is discussed in [py-googletrans/234](/ssut/py-googletrans/issues/234). They mention an alpha release version which currently works around the problem in [py-googletrans/issues/280](https://github.com/ssut/py-googletrans/issues/280) but it looks like google has done this a [few times before](https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group). I'll try to roll the alpha into the new image but this might come back.

**Comment by misterhay** [comment]
> As far as I can tell this is down to google (repeatedly) changing their API. The same issue is discussed in [py-googletrans/234](/ssut/py-googletrans/issues/234). They mention an alpha release version which currently works around the problem in [py-googletrans/issues/280](https://github.com/ssut/py-googletrans/issues/280) but it looks like google has done this a [few times before](https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group). I'll try to roll the alpha into the new image but this might come back.
> 
> EDIT: I've updated the image on hub.callysto.ca can you try deploying this again and see if it still fails?

It worked, thank you :)

**Review by byrcyb — APPROVED** [review]
Looks good to me. Pretty fun little notebook.

**Review by byrcyb — APPROVED** [review]

**Pull request merged**
