### PR TITLE
Iterative Algorithms notebooks

### PR DESCRIPTION
**Pull request by mrbubbleman**
Based on the following story: [https://jira.cybera.ca/browse/CC-2618](url)

Notebook contains the following:
- Implementation of multiple searching and sorting algorithms
- Explanations of time complexity
- Debugging practices/error identification
- Algorithm development based on modifications

### CODE REVIEW

**Comment by mlamoureux** [comment]
Two things. 1) Mention that the "O" notation stands for "Order of complexity."
2) Give some real examples of sorting that students or teachers can relate to. For instance, when playing cards (like bridge or poker or whatever), you can have a dozen cards in your hand and you want to sort them. The natural thing that most people do is "insertion sort." That is, you start with one card, insert the next card in order, then take the third card and insert it in order, and keep going until all the cards are inserted in order. I like that example as it is easy for students to do and to relate to. Funny thing is that no one uses "bubble sort" to sort they cards. Why not? Well, for one thing, it is pretty slow. For another thing, we can look at ten cards in order and see right away where the 11-th card belongs. Our brain works like that. Bubble sort was designed for computers that can only compare two things at a time. A second example is something teachers do all the time: take a stack of exam papers and sort them alphabetically before entering the grades in a grade book, or before returning them to students. (I did this all the time as a prof.) For a small class, like twenty students (so twenty exam papers), you can quickly sort via insertion sort. Just like that cards. For a big class, like 100 students, or two hundred, a good way is to do a "divide and conquer" method. Split the pile of 100 papers into 4 piles of roughly 25 each. Sort each pile using insertion sort. Then merge the 4 piles by placing them side by side, look at the four papers on the top and pick the first one in order, then look at what is left (three papers are still on top, and then there is a new one that was uncovered when you picked up one paper), and so pick the second one in order. And continue. This is called a "merge sort." It is pretty fast. For a really big class, you might go through the pile of 1000 papers and pick out all the names that start with A and make that into a pile. Then a B pile, then a C pile, etc. Then sort each of the 26 piles (insertion sort, perhaps). Then the piles are all in order. Combine by stacking A on top of B on top of C.

**Comment by mlamoureux** [comment]
Anyhow, these are good examples of how we sort things in practice, and real some of the ideas behind sorting algorithms.
    I also think it is really funny that I teach with other mathematicians, and some of them have NO IDEA on how to speed up sorting with exam papers. They will do an insertion sort with 1000 papers. Crazy crazy!!

**Comment by TeppieC** [comment]
1. In the second hint for linear_search function, a closing quotation is missing (```), making the code block not rendered. This also happens in other hint cells.
2. Should the 2nd hint be the solution? If so, the function was named as `linear_search_test` not `linear_search`. If students use this solution, they would have error in the next section when they run `test_linear_search`. 
3. As per the requirement for `linear_search` function, if a value was not found, return value will be -1; if a value was found, return value will be a list `[target, index]`. However, in the `test_linear_search` function definition, it always compares the return value of `linear_search` to a integer (test case 1 and 3 won't pass). Please make the return values consistent, for example,  `return [target, -1]` if not found and check for `linear_search(arr, target)[1]`
4. Solution for selection sort won't pass the test case 1 and 3.
5. Do you want to also add hint&solutions to the `binary_search` challenge?
6. In Problem-Solving: Debugging section, the `contains_duplicate_error` function wasn't rendered in a code cell, it's in a markdown. Actually I'm a bit confused when first reading this question and the "---> Error" notations. Maybe we can make it more clear, just tell them the `contains_duplicate_error` won't work properly, modify the `contains_duplicate_error` function to let it pass all tests? And this question also need a solution/hint.
7. Same for insertion sort. Since you provided a solution and it's named as `insertion_sort_error`, it would be great if you can keep using this name in the following `test_insertion_sort` function. And the solution function definition needs a return value.

**Comment by TeppieC** [comment]
Thanks for the edition, Eric! There's still a few things needed to be changed:

1. selection sort still didn't work. Test case 1 and 3 failed. 
2. For selection sort, the return value left in the empty function definition was list_of_nums, but the solution is arr. Please make this consistent so that students can use the solution directly. 
3. the second solution of contains_duplicate_error didn't pass test case 2 and 3

**Comment by TeppieC** [comment]
Thanks Eric, one last minor change: the first two lines of selection_sort should be list_of_nums not length_of_nums.
```
def selection_sort(list_of_nums):
    length_of_nums = len(list_of_nums)
```

**Comment by mrbubbleman** [comment]
Apologies about all the mistakes! Hopefully everything should be working without errors now.

**Review by misterhay — APPROVED** [review]
Looks good to me

**Pull request merged**
