### PR TITLE
Cc 67 probability experiment

### PR DESCRIPTION
**Pull request by lgfunderburk**
I could not find this notebook in the main webpage. 
Is it weird that I am bumping a notebook I developed? 
I really enjoyed creating this notebook, would be happy to make improvements before merging - and also add to the list of notebooks in the spreadsheet :).

### CODE REVIEW

**Comment by lgfunderburk** [comment]
Notebook
https://github.com/callysto/curriculum-notebooks/tree/CC-67-Probability-Experiment/Mathematics/ProbabilityExperiment

**Comment by misterhay** [comment]
Looks good, but a few suggestions:
- delete the banner images and instead (https://github.com/callysto/curriculum-notebooks/blob/master/CONTRIBUTING.md#banners)
- move the top banner to above the "hide code" code
- mixing markdown with html doesn't always render correctly
- change the name of the function "get_lucky", that might cause some unnecessary giggling in a junior high context
- Some of the wording and mathematical notation is a little too advanced for Grade 7, check out some online examples of teacher-created activities and perhaps a commercial textbook

**Comment by lgfunderburk** [comment]
Need someone to approve changes if they look good. 
Removed excess definitions, updates grades, updated banners, and renamed the get_lucky function.

**Comment by misterhay** [comment]
I added an "Open in Callysto" button and made some minor typographical changes (e.g. where a ** was missing to close a bold tag).

In the "Probabilites as fractions, ratios and percents" interactive, when `Size of sample space:` is set to `Eight` the "Probability of each event" text overlaps with the `P(1) =` line.

The `Even or Odd Sum Probability Experiment:` is giving an error: "No handles with labels found to put in legend."

As well, Question 7 and Question 8 use the same variable names which may cause issues if the the `Record Answer` buttons are clicked in the wrong order.

Other than those minor issues, though, it looks good.

**Comment by lgfunderburk** [comment]
@misterhay made changes as outlined. 
Re-review and let me know if there are further issues.

**Pull request merged**
