### PR TITLE
Create a plot generating notebook.

### PR DESCRIPTION
**Pull request by misterhay**

### CODE REVIEW

**Comment by byrcyb** [comment]
Definitely fun to generate these different story plots. Is the purpose of the notebook to learn about (constructing) story plots?

**Comment by byrcyb** [comment]
Also it might be nice to add something like this so they know they can generate another story plot 

`You can ▶Run the cell again to generate another story plot idea too.`

**Comment by misterhay** [comment]
> Definitely fun to generate these different story plots. Is the purpose of the notebook to learn about (constructing) story plots?

This was inspired by http://www.scholastic.com/teachers/story-starters as a way to encourage students to write different stories.

**Review by byrcyb — APPROVED** [review]
Changes look good, sorry it took so long to approve and merge this.

**Pull request merged**
