### PR TITLE
CC-193-GeometryBasic5

### PR DESCRIPTION
**Pull request by vincentcote87**
Notebook on the topic of time. Ready for review.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
A comment on the Initialize button: this was a task in Jira that was assigned to Vincent this summer -- to come up with a 'magic' button that would allow users to bypass the menu. (In theory this would mean no longer having to tell users to run all cells.)
At some point this was part of adding some infrastructure to make the interface more user-friendly.

In any case, Vincent was assigned that task, and he developed the button as requested. Since he went to the trouble of creating it, I guess reasonably, he's used it in all his notebooks since.
But for whatever reason (maybe because the tools in nbplus are not well advertised?) nobody else has bothered to use it, so all notebooks except for Vincent's fall back on using the menu.

**Comment by sean-fitzpatrick** [comment]
Also, I also don't know why time was included under geometry basics, but the task in Jira that this notebook is for quite clearly asks for a notebook on time.
This was a teacher-contributed topic, I believe. There were 5 tasks on Jira from the same teacher that were all provided under the heading of 'geometry basics'.
So maybe we can fault the original topic submission -- either the teacher who contributed it, or the person who created the task in Jira -- but as the task was laid out in the CC-193 task in Jira, Vincent has done exactly what was asked in the description.

**Comment by vincentcote87** [comment]
I have added the YouTubeVideo import, is there a way to center the video within the cell? Also is there a way to keep the original aspect ratio, I tried adding just width hoping it would set the height automatically. 

I have tried using the import HTML, for the time guessing time widget it worked flawlessly. For the other two widgets the graphics are not showing up, maybe an issue with html canvas? I have left the html files in there if you want to import them into the notebook to see for yourself.

Thanks!

**Comment by inygy** [comment]
I think Arcotbha was talking about this YouTube import code 
`from IPython.display import YouTubeVideo`
`YouTubeVideo('9ZzkMIrWdPE', width=800, height=550)`
The keyword `None` or similar for the width and height may keep the original aspect ratio.
`width=100%` or width: `100%` will often autosize, however, it does not work for this particular YouTube Ipython.display function. 
I do like how your custom magic checks the video is working, something Ipython.display does not have built in.

For the HTML imports be sure you are doing it in two lines:
`from IPython.display import HTML` 
`HTML(filename='TimeGuessWidget.html')`
The above code works when I run it, let me know if it works for you or if it is still throwing an error. Use the HTML if it does work.

I like the `more` button you included. Could you add the magic for it to nbplus? A common piece of feedback from teachers is that they want “less text” so the `more` button is a nice compromise.

**Comment by vincentcote87** [comment]
Thanks India, 

I thought calling `from IPython.display import HTML` once up top was enough, I am re-importing it with each new HTML file now and it works perfectly. I am glad you like my youtube import magic, it also centers the video and gives it a subtle shadow. For this current revision I have kept it out as per the initial request of this PR, if you prefer the magic over the IPython Youtube let me know and I will change it back. 

I have not played around with nbplus much but I can incorporate my "more" button in there for sure! Do you think you could add a story for this on Jira and assign it to me?

**Pull request merged**
