### PR TITLE
Cc 103 light transmission

### PR DESCRIPTION
**Pull request by lfunderburk**

### CODE REVIEW

**Comment by lfunderburk** [comment]
_Re: Is there a way to get rid of the large amount of white space before the wave animation?_

Changed figsize, does this help?

_Re: Sentence on Travels through medium... has the word 'either' twice, which makes the sentence not work.
Spelling error in response to Question 1 - 'relfection'._

Corrected

_Re: I really like the refraction widget._

Thank you :) 

_Re: Need more explanation of the cell titled 'Optical Technologies'. It isn't clear what motivates the inclusion of the cell._

I was not sure from the description what they wanted, so I simply listed them. I think that goal is covered in more depth in CC-104 

_Re: Have you considered doing the visuals/widgets in GeoGebra? They are much smoother there. However, they work well in this notebook and the choice is up to you._

I was intrigued but did not really explore GeoGebra meets Jupyter Notebooks in more depth. I tried a few times but was discouraged by the fact that I needed Javascript, tried to install and exceeded disk quota on my hub,callysto server. Is there a way around this?

**Comment by snimpids** [comment]
Have you contacted Richelle or Byron about clarifying the part about optical technologies? I know that they are covered in more depth in CC-104, so I'm also not sure how much to say about them.

About exceeding the disk quota: if you're finding that installing packages is causing problems, you can ask Ian Allison via Slack to increase your disk quota. Also, you can check out the notebook by Evan MacNeil on function reflections to see how he included GeoGebra applets without external packages.

**Comment by lfunderburk** [comment]
https://github.com/callysto/curriculum-notebooks/blob/CC-103-LightTransmission/Physics/LightTransmission/transmission-of-light.ipynb

Need teachers to revise but at the time no one is available. 

From our team, no further changes will be made. 

I am creating a pull request for this branch.

**Comment by snimpids** [comment]
Merging for now, and we'll await feedback from teachers during the testing phase.

**Pull request merged**
