### PR TITLE
Coast salish baskets

### PR DESCRIPTION
**Pull request by mlamoureux**
Ready for review.
New code for creating Coast Salish Baskets, all Python, all visible to the user.
More responsive user interface, for a better user experience.
Includes code to save images (both .png and live 3D renderings in .html file)
Tested on JupyterHub and JupyterLab on Mac, and 2i2c. 
Tested on JupyterHub on hub.callysto.ca

### CODE REVIEW

**Comment by mlamoureux** [comment]
Looking for a reviewer to test the code before merging, just to be safe.

**Comment by mgrant46** [comment]
I will do it.

**Comment by misterhay** [comment]
Do we need the `images/no_used` folder, or can it be deleted?

**Comment by mlamoureux** [comment]
> Do we need the `images/no_used` folder, or can it be deleted?

No, it cane be safely deleted.

**Review by byrcyb — APPROVED** [review]
Changes look good, and more interactive than before.

**Pull request merged**
