### PR TITLE
Cc 86 binary decimal conversion

### PR DESCRIPTION
**Pull request by inygy**
>@sean-fitzpatrick: CC-86 was done by Rafat Islam, who is no longer working for Callysto. (Aside from adjusting the GeoGebra code, Rafat finished this before he left.) Vincent is submitting the pull request on his behalf. 

I replaced Vincent's PR #58 with this one to fix the branch source and target. Vincent is still the primary assignee.

### CODE REVIEW

**Comment by vincentcote87** [comment]
I am confused about these merge conflicts, how come this branch has conflicts with other notebooks that have nothing to do with this one? Trying to merge them manually is proving to be a bit of a nightmare. I think maybe a clean pull request adding this notebooks files manually into a a newly updated staging branch might be an easier solution?

**Comment by sean-fitzpatrick** [comment]
Yeah, I'm not sure what exactly Rafat was doing when he made the branch. Maybe he merged a bunch of different things into his Jupyter directory before creating the branch?
It's probably easiest to set aside his files, make a clean branch with those files, and go from there.

**Comment by nickurak** [comment]
I spent a little time looking at this, trying to figure out how something like this would happen, and didn't really reach anything specific, but have some suggestions to help avoid this sort of thing all the same (see below).

I did create a filtered-down version of the git history that includes only the relevant changes, rebased on top of current staging branch. That shows the history of this PR as it was probably intended.

That's in my `cleanup-CC-86-Binary-Decimal-Conversion` branch.

That could be pushed over top of this PR's branch (`git push --force origin origin/cleanup-CC-86-Binary-Decimal-Conversion:CC-86-Binary-Decimal-Conversion` should do the trick) to correct this PR in-place, or a new PR could be created. We may also find that those changes in individual commits don't really add value in this case, and a squashed set of them all would be better. I'll lean on the judgement of folks who've been working in this space longer than I have.

I still think this might be an opportunity to think about adapting some practices to help:

- It's been my experience that long-running branches like this one (which started almost 6 months ago) raise the risk of changes happening unexpectedly underneath you, and we're kind of lucky this runs at all today on top of master, given how long it's been.
- If you're going to have a branch for more than a few days, you should be rebasing regularly to make sure your changes inherit things that have happened upstream. `git pull --rebase` is the common way of doing that. If you have merge conflicts, you should try to hit them as early as possible, and have a larger number of *small* merge conflicts to resolve. (Some folks advocate a normal `git pull`, which creates merge-commits to pull upstream's changes into your branch -- I have strong opinions about that I can go into in another setting ;) )
- We should focus on getting small bits of work started, and finished, in small timeframes. I'm not sure if Rafat just had a very small amount of time to spend on this work, stretched out over many months, or if he was multitasking with this and other work, but either way that's a challenging ecosystem in which to produce any artifacts of work, and should be avoided.

**Comment by nickurak** [comment]
At Robert Petry's advice, I've gone ahead and pushed my updated/reprocessed versions of these commits to this PR. The original contents are available in the `CC-86-Binary-Decimal-Conversion-nickurak-backup` branch.

This should be significantly easier to review for correctness and appropriateness.

**Comment by sean-fitzpatrick** [comment]
I can look at the GeoGebra applets (I created the applet Rafat included) but I'm swamped right now getting my spring courses off of the ground.
 A general comment: if we can come up with code that checks for a module before doing the pip install, I would suggest asking for this to be included in the developers' guide, and in the nbplus documentation. The current code (with the force install) is copied from the instructions in the nbplus repo.

Specific comments: I'm not sure about the Python code that's failing (that's not my expertise!) so it would be good if someone can take a look at it. It did work at some point, so I wonder what changed to break it.
The second hide code HTML is there because I couldn't talk Rafat out of including it. He seemed to think that if someone wanted to play with the code in the second half of the notebook, they wouldn't want to have to scroll all the way to the top. Rafat is not on the project any more, so we can safely kill that code block.

**Pull request merged**
