### PR TITLE
Statistics project

### PR DESCRIPTION
**Pull request by misterhay**
Copied from https://github.com/misterhay/math-20-2, a statistical research project for high school math students.

### CODE REVIEW

**Comment by misterhay** [comment]
The TravisCI failure is because of
```
!pip install --user pytrends                     
from pytrends.request import TrendReq
```
not being recognized, but this works in the Callysto Hub.

**Comment by lgfunderburk** [comment]
@misterhay for example-project-income-per-person:
The spreadsheet ID... is it unique to the Google API credentials for the author? If the account was not active anymore for whatever reason, would the key be deactivated? Might be a good idea to add a link on how to create your own key. 
The rest of the notebooks look great. I like the project outline.

**Comment by lgfunderburk** [comment]
The same comment would apply to gapminder.ipynb - where a Google API key is provided.

**Comment by lgfunderburk** [comment]
nhl notebook also throws an error in the second cell 
`ValueError: Passed header=1 but only 1 lines in file`

**Comment by lgfunderburk** [comment]
This notebook mapping-tree-locations struggled with the number of data points that were passed - and the kernel died/restarted. Might be worth decreasing the total number of data points that are plotted.

**Comment by misterhay** [comment]
The Google Spreadsheet keys (and GUIs) are identifiers for those particular spreadsheets that we are downloading data from (e.g. `https://docs.google.com/spreadsheets/d/11mulzUH3_cueq-V9D5KIlo9oHE9YYZrUSeVyCin7_rM/edit#gid=176703676`), they are not API credentials. Since these are publicly available sheets there is no need for an API, we're instructing Python to download a CSV file.

**Comment by mlamoureux** [comment]
I'm curious about the student names: Annya Marx ( in example-project-income-per-person) and Flor Nightgale (in example-project-soccer). Are these real people? Are we violating any privacy in using their real names?

**Comment by misterhay** [comment]
> I'm curious about the student names: Annya Marx ( in example-project-income-per-person) and Flor Nightgale (in example-project-soccer). Are these real people? Are we violating any privacy in using their real names?

Those are just made up names. For the income project I was reference Karl Marx and "on your marks", and Flor Nightgale is a reference to the statistician Florence Nightingale :)

**Comment by misterhay** [comment]
> nhl notebook also throws an error in the second cell
> `ValueError: Passed header=1 but only 1 lines in file`

It seems that with the updated NHL season there aren't as many players, so the number of data pages changed. I've added error handling to deal with that.

**Comment by misterhay** [comment]
> This notebook mapping-tree-locations struggled with the number of data points that were passed - and the kernel died/restarted. Might be worth decreasing the total number of data points that are plotted.

Number of trees in sample decreased to 200, that should make it a little faster.

**Comment by misterhay** [comment]
Changes should be complete at this point, thank you for the reviews and suggestions.

**Comment by mlamoureux** [comment]
I'm still getting inconsistent behaviour with the notebook google-search-trends. The pip command seems to install module "pytrends" correctly (Requirement already satistified), but the import occassionally fails, with this message:
----> 2 from pytrends.request import TrendReq
      3 import pandas as pd
      4 
      5 pytrend = TrendReq()

ModuleNotFoundError: No module named 'pytrends'

Sometimes it works, sometimes not. I don't see a pattern. This is also the place where the "continuous integration" check is failing.

**Comment by mlamoureux** [comment]
More on the notebook google-search-trends. 1 unsuccessful import this morning, followed by 3 times successful import. (pytrends module) Maybe it fixed itself? Anyhow, I can no longer get the unsuccessful import. Weird.

**Comment by misterhay** [comment]
> More on the notebook google-search-trends. 2 unsuccessful imports this morning, followed by 3 times successful import. (pytrends module) Maybe it fixed itself? Anyhow, I can no longer get the unsuccessful import. Weird.

Very strange. It looks like if it's not installed then you need to restart the kernel after installing, but other than that I haven't been able to replicate unsuccessful imports.

Perhaps we can add `pytrends` to the list of libraries to install during the next Callysto Hub maintenance.

**Comment by lgfunderburk** [comment]
Tested notebooks, NBA notebook fails for URL `https://www.espn.com/nba/stats/team/_/table/offensive/sort/avgPoints/dir/desc`

when I visit the site there are no tables. Python error reflects the same `ValueError: No tables found `

**Comment by lgfunderburk** [comment]
It also seems like gapminder notebook sometimes pulls the data, sometimes it doesn't - similar to the pip install commands. 
I am wondering if it makes more sense to download the spreadsheet and add it as a file, instead of pulling from the web. This would apply to gapminder, NBA and NHL notebooks, where data pulling was an issue if the data was removed from the server.

**Comment by lgfunderburk** [comment]
for the pip command, I wonder if instead of installing locally, we add it as a list of modules to have available in the Callysto hub. 
Thoughts @byrcyb ? 
The python library causing issues is pytrends

**Comment by byrcyb** [comment]
> Very strange. It looks like if it's not installed then you need to restart the kernel after installing, but other than that I haven't been able to replicate unsuccessful imports.

I think the unsuccessful imports are because the `!pip install pytrends` and the `from pytrends.request import TrendReq` are in the same code block. If I separate `!pip install pytrends` into a separate code cell and run all then I have no problems. 

This is probably going to be moot as we will be installing `pytrends` for everyone on August 29th but at least in the meantime we should have the install in a separate code cell.

**Comment by byrcyb** [comment]
> Tested notebooks, NBA notebook fails for URL `https://www.espn.com/nba/stats/team/_/table/offensive/sort/avgPoints/dir/desc`
> 
> when I visit the site there are no tables. Python error reflects the same `ValueError: No tables found `

@lgfunderburk  This is a bit of a head scratcher. Both the website url and notebook code work for me. I wonder if your errors have something to do with the connection, browser (I'm using Chrome with uBlock Origin) or VPN or other?

**Comment by byrcyb** [comment]
The `example-project-soccer.ipynb` is awesome but there's no data for 2020-2021 on ESPN so nothing really gets displayed if you try to run all cells. Everything works great if however you change url to the 2019-2020 season or earlier, and the way it's coded it will work in the future assuming everything's back to normal.

**Comment by byrcyb** [comment]
For `statistics-project.ipynb` I really like it and it would be cool to see the students working their way through this. My only comment would be that if they want to use primary data, survey people and include any personal information then they'll need to get consent. So perhaps add a warning about collecting any personal information.

**Pull request merged**
