### PR TITLE
Covid 19

### PR DESCRIPTION
**Pull request by lgfunderburk**
Added sunburst notebook and plots for world COVID-19 data on confirmed and deaths. 
Please review. 
Notebook under
/Science/COVID-19

### CODE REVIEW

**Comment by misterhay** [comment]
Hope you don't mind that I made some changes. I'm hoping the final graph as percents might be clearer than as an index. As well, the graph might be easier to read if the countries are sorted by confirmed cases. I didn't try that, though, so I'm not sure.

To avoid the Travis error, perhaps we should `!pip install` all the required modules (although I like the `try: except:`) since `pip` will be fine even if the modules are already installed.

**Comment by lgfunderburk** [comment]
Thank you @misterhay!
Looking at changes.

**Comment by lgfunderburk** [comment]
Yeah, I am not sure what the best way to handle missing dependencies is. Could add an extra cell to pip install, and comment out once the notebook has passed Travis testing.

**Comment by misterhay** [comment]
I don't think the `!pip install` needs to be in a separate cell or commented out. Correct me if I'm wrong, but if dependencies are already met then there's no harm in running it again.

**Comment by lgfunderburk** [comment]
Added them as `pip`. 
I agree that there is no harm in installing them again. However, dependencies need to be installed once. Afterwards they can be commented out - added a note in the markdown cell above. 

Tried running pd.json_normalize but that threw an error at me. Uncommented `from pandas.io.json import json_normalize`

**Comment by misterhay** [comment]
Regarding the json_normalize, with `pandas 1.0.1` I get the notification `pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead`, but Callysto Hub has `pandas 0.25.3` installed. A `!pip install --user pandas` will take care of that. Maybe we should add `--user` to all of those pip installs.

Pandas is something we should upgrade on the Hub at some point, though.

**Comment by lgfunderburk** [comment]
Added --user flag and tested on hub.callysto.ca
--user flag raises error in Travis test

**Comment by lgfunderburk** [comment]
Added one more notebook with log scale cases per country

**Comment by lgfunderburk** [comment]
@byrcyb corrected and tested log curve notebook in the Hub
please revise
will add modified sunburst notebook shortly

**Comment by lgfunderburk** [comment]
@byrcyb  removed second set of plots in sunburst plot as @misterhay  per capita analysis approaches the question in a much more tactful way. Left sunburst plot only.

**Comment by lgfunderburk** [comment]
Please review. 
If it looks good, and travis testing passes, we could merge to master. I'd be happy to create links for the notebooks.

**Pull request merged**
