### PR TITLE
CC-1888 Minor updates

### PR DESCRIPTION
**Pull request by meghbali**

### CODE REVIEW

**Review by misterhay — CHANGES_REQUESTED** [review]
Since both of these wage amounts are indexed to inflation, maybe we should change it to a statement like "For instance, in October of 2021 Saskatchewan's minimum wage increased to $11.81 per hour."

**Comment by misterhay** [comment]
Have a look at the added `solver` and let me know what you think.

**Comment by meghbali** [comment]
> Have a look at the added `solver` and let me know what you think.

Thanks David, I will review this now.

**Comment by meghbali** [comment]
The solver looks good. Just fixed a minor error.

**Review by misterhay — APPROVED** [review]
Looks ready to merge.

**Pull request merged**
