### PR TITLE
Fixes and improvements for test script

### PR DESCRIPTION
**Pull request by cmann**
After seeing the results of [build #9](https://travis-ci.org/callysto/curriculum-notebooks/builds/486187526?utm_source=github_status&utm_medium=notification) I realized there's a few problems with the test script and found a couple more while fixing those:

* If multiple notebooks are tested, the script now returns a non-zero exit code if any fail. Previously only the result of the final test mattered.
* Ignore notebooks in `.ipynb_checkpoints` directories when `$TRAVIS_COMMIT_RANGE` is present
* Spaces in notebook paths no longer break the script
* Removed dependency on `$TRAVIS_BUILD_DIR` so the script can be run locally without modification
* Now also checks if the script itself has been modified and if so will always trigger a full run

### CODE REVIEW

**Comment by cmann** [comment]
Okay, this can be merged pending review. The check should fail since not all notebooks pass testing yet.

It also turns out I missed a few notebooks that test successfully locally but fail in the Travis environment. All of the failures appear to be due to permissions issues with loading external files. I'll open a new issue for those.

**Comment by cmann** [comment]
I agree, there shouldn't be any in the repository. They're in `.gitignore` now so it's a problem that will disappear as older branches are merged. I like the idea of an explicit check that fails if there's any committed to the repo though. I think ignoring them for the `py.test` component is still beneficial since the tests can be run locally where checkpoint directories can legitimately exist.

**Comment by inygy** [comment]
There also should not be spaces in notebook paths, can we flag those as a failure?

**Comment by cmann** [comment]
I've added the checks for whitespace in notebook paths and the existence of `.ipynb_checkpoints` directories. I also removed some additional checkpoint directories the new check found.

**Pull request merged**
