### PR TITLE
Cc 20 numbersense

### PR DESCRIPTION
**Pull request by ekce**
The notebook is ready for review.

### CODE REVIEW

**Comment by inygy** [comment]
`ModuleNotFoundError: No module named 'geogebra'` on restart run-all with a fresh hub

**Comment by ekce** [comment]
I created a fresh Callysto Hub and installed the package from nbplus according to the directions on the nbplus repository. In other words, by opening a terminal on the hub and running:
```
pip install --upgrade --force-reinstall --user git+git://github.com/callysto/nbplus.git#egg=geogebra\&subdirectory=geogebra
```

I added a small update to remove an option that is broken in the master branch of the geogebra package on nbplus. Here is a screenshot of the notebook working after the update on a fresh hub with the geogebra package installed and the latest update.
cc-20-numbersense - nbplus master - after update

If you like I could rewrite the notebook to not use the geogebra package and embed geogebra directly using html magics.

On a sidenote, there is the possibility of a race condition occurring when running notebooks that use the nbviz javascript libraries using `restart run-all`. If a race condition does occur then some visualizations may fail to load initially (but ought to work if the cell is re-run manually). This is because javascript is by nature asynchronous and it fails silently. I've been working on a solution in a local branch (not currently pushed to the repository) of my geogebra package but it's far from ideal since javascript isn't really meant to be used this way.

**Comment by inygy** [comment]
If we choose to go with the pip install it should be included directly in the notebook so the notebook can work out of box. As for the HTML import see issue #64 
I would like to have a consistent way of importing through all the notebooks, which one is more stable?

Race conditions pose a bit of a challenge, I know @ericeasthope was looking into them as well. Is there a feasible solution there or should we try to avoid/compensate for them instead?

**Comment by tatianameleshko** [comment]
Added geogebra install to the notebook in form :
_try:
    from geogebra.ggb import *
except ImportError:
    !pip install --upgrade --force-reinstall --user git+git://github.com/callysto/nbplus.git#egg=geogebra\&subdirectory=geogebra
    from importlib import reload
    import site
    reload(site)
    from geogebra.ggb import *    
ggb = GGB().setDefaultOptions(enableShiftDragZoom=False)_
+ some latex fixes.. Done' see any issues with race condition

**Pull request merged**
